  server:
    port: 8081

  spring:
    application:
      name: eurka-server
    security:
      user:
        name: xiaoxinmo
        password: xiaoxinmo



  eureka:
    instance:
      hostname: localhost
    client:
      # 由于该应用为注册中心, 所以设置为false, 代表不向注册中心注册自己
      registerWithEureka: false
      # 由于注册中心的职责就是维护服务实例, 并不需要检索服务, 所以也设置为 false
      fetchRegistry: false
      serviceUrl:
        defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}/eureka/
    server:
      enable-self-preservation: false #关闭保护模式
      eviction-interval-timer-in-ms: 6000 #默认60清理一次

